version: "3.8"
services:
  database:
    container_name: mysql_crm
    image: mysql:8.0.24
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_USER: felipe
      MYSQL_PASSWORD: secret
    restart: always
    ports:
      - 3306:3306
    volumes:
      - crmdata:/var/lib/mysql
    networks:
      - crm
networks:
  crm:
    driver: bridge
volumes:
  crmdata:
    driver: local
